from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parents[1] / "scripts"
CORE = SCRIPT_DIR / "agents_overlay_context.py"
KIRO = SCRIPT_DIR / "kiro_cli_overlay.py"

GENERATED_OWNER = (
    "<!-- generated by agents-local-overlay from the primary AGENTS.local.md; do not edit -->"
)
KIRO_OWNER = "<!-- generated by agents-local-overlay; do not edit -->"

MODULE_TMP = tempfile.TemporaryDirectory(prefix="agents-overlay-v2-test-")
MODULE_ROOT = Path(MODULE_TMP.name)
FAKE_BIN = MODULE_ROOT / "bin"
EMPTY_CODEX_HOME = MODULE_ROOT / "codex-home"
EMPTY_CODEX_HOME.mkdir()
EMPTY_HOME = MODULE_ROOT / "home"
EMPTY_HOME.mkdir()

FAKE_CLI_SCRIPTS = {
    "claude": 'echo "2.1.235 (Claude Code)"',
    "codex": "echo codex-cli 0.147.0",
    "kiro-cli": (
        'if [ "$1" = "settings" ] && [ "$2" = "list" ]; then\n'
        '  printf \'%s\\n\' \'{"chat.disableInheritingDefaultResources": false}\'\n'
        "  exit 0\n"
        "fi\n"
        "echo 2.15.1"
    ),
}


def write_cli_bin(dirpath: Path, scripts: dict) -> Path:
    dirpath.mkdir(parents=True, exist_ok=True)
    for name, body in scripts.items():
        script = dirpath / name
        script.write_text(f"#!/bin/sh\n{body}\n", encoding="utf-8")
        script.chmod(0o755)
    return dirpath


write_cli_bin(FAKE_BIN, FAKE_CLI_SCRIPTS)


def isolated_env(extra: dict | None = None) -> dict:
    env = os.environ.copy()
    for key in list(env):
        if key.startswith("AGENTS_OVERLAY_"):
            env.pop(key)
    env.pop("CLAUDE_CODE_DISABLE_CLAUDE_MDS", None)
    env["GIT_CONFIG_GLOBAL"] = "/dev/null"
    env["GIT_CONFIG_SYSTEM"] = "/dev/null"
    env["CODEX_HOME"] = str(EMPTY_CODEX_HOME)
    env["HOME"] = str(EMPTY_HOME)
    env["PATH"] = f"{FAKE_BIN}:{env['PATH']}"
    if extra:
        env.update(extra)
    return env


def run_core(
    args: list[str],
    cwd: Path,
    stdin: str = "",
    extra_env: dict | None = None,
) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(CORE), *args],
        cwd=str(cwd),
        input=stdin,
        capture_output=True,
        text=True,
        env=isolated_env(extra_env),
        timeout=60,
    )


def run_git(cwd: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-c", "user.email=t@example.test", "-c", "user.name=t", *args],
        cwd=str(cwd),
        check=True,
        capture_output=True,
        env=isolated_env(),
    )


def make_repo(base: Path, name: str = "repo", local: bool = True) -> Path:
    repo = base / name
    repo.mkdir()
    run_git(repo, "init", "-q")
    (repo / "AGENTS.md").write_text("# shared\nshared rule X\n", encoding="utf-8")
    if local:
        (repo / "AGENTS.local.md").write_text("# local\nlocal rule Y\n", encoding="utf-8")
    run_git(repo, "add", "AGENTS.md")
    run_git(repo, "commit", "-qm", "init")
    return repo


def hook_stdin(cwd: Path, **fields) -> str:
    return json.dumps({"cwd": str(cwd), **fields})


def make_ignored_shared_repo(base: Path) -> Path:
    repo = base / "repo"
    repo.mkdir()
    run_git(repo, "init", "-q")
    (repo / "README.md").write_text("readme\n", encoding="utf-8")
    run_git(repo, "add", "README.md")
    run_git(repo, "commit", "-qm", "init")
    (repo / "AGENTS.md").write_text("# shared\nshared rule X\n", encoding="utf-8")
    (repo / "AGENTS.local.md").write_text("# local\nlocal rule Y\n", encoding="utf-8")
    return repo


def hook_context(proc: subprocess.CompletedProcess) -> str:
    payload = json.loads(proc.stdout)
    return payload["hookSpecificOutput"]["additionalContext"]


CLAUDE_SESSION = ["json", "SessionStart", "CLAUDE.md", "CLAUDE.local.md", ".", "claude-session"]
CLAUDE_SUBAGENT = ["json", "SubagentStart", "CLAUDE.md", "CLAUDE.local.md", ".", "claude-subagent"]
CODEX_SESSION = ["json", "SessionStart", "AGENTS.md", "-", ".", "codex-session"]
CODEX_SUBAGENT = ["json", "SubagentStart", "AGENTS.md", "-", ".", "codex-subagent"]


class OverlayTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory(prefix="agents-overlay-case-")
        self.base = Path(self._tmp.name).resolve()
        self.addCleanup(self._tmp.cleanup)

    def setup_repo(self, repo: Path) -> subprocess.CompletedProcess:
        proc = run_core(["setup"], repo)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        return proc

    def add_worktree(self, repo: Path, name: str = "wt") -> Path:
        target = self.base / name
        run_git(repo, "worktree", "add", "-q", str(target))
        return target.resolve()


class SetupTests(OverlayTestCase):
    def test_creates_bridges_ignores_and_passes_verify(self) -> None:
        repo = make_repo(self.base)
        proc = self.setup_repo(repo)
        self.assertEqual((repo / "CLAUDE.md").read_text(encoding="utf-8"), "@AGENTS.md\n")
        self.assertEqual(
            (repo / "CLAUDE.local.md").read_text(encoding="utf-8"), "@AGENTS.local.md\n"
        )
        gitignore = (repo / ".gitignore").read_text(encoding="utf-8")
        for pattern in ("AGENTS.local.md", "CLAUDE.local.md", ".kiro/steering/agents-local-overlay.md"):
            self.assertIn(pattern, gitignore)
        self.assertIn("verify: OK", proc.stdout)

    def test_requires_a_rule_source(self) -> None:
        repo = self.base / "empty"
        repo.mkdir()
        run_git(repo, "init", "-q")
        proc = run_core(["setup"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("create AGENTS.md and/or AGENTS.local.md", proc.stderr)

    def test_normalizes_crlf_bridge(self) -> None:
        repo = make_repo(self.base)
        (repo / "CLAUDE.md").write_bytes(b"@AGENTS.md\r\n")
        self.setup_repo(repo)
        self.assertEqual((repo / "CLAUDE.md").read_bytes(), b"@AGENTS.md\n")

    def test_rejects_bridge_with_extra_content(self) -> None:
        repo = make_repo(self.base)
        (repo / "CLAUDE.md").write_text("@AGENTS.md\nmore prose\n", encoding="utf-8")
        proc = run_core(["setup"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("content beyond the @AGENTS.md import", proc.stderr)
        self.assertEqual(
            (repo / "CLAUDE.md").read_text(encoding="utf-8"), "@AGENTS.md\nmore prose\n"
        )

    def test_materializes_generated_copy_in_linked_worktree(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        copy = (worktree / "CLAUDE.local.md").read_text(encoding="utf-8")
        self.assertTrue(copy.startswith(GENERATED_OWNER + "\n"))
        self.assertIn("local rule Y", copy)

    def test_removes_orphan_generated_copy(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        (repo / "AGENTS.local.md").unlink()
        proc = self.setup_repo(repo)
        self.assertIn("removed orphan generated copy", proc.stdout)
        self.assertFalse((worktree / "CLAUDE.local.md").exists())

    def test_second_run_changes_nothing(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        proc = self.setup_repo(repo)
        self.assertNotIn("changed:", proc.stdout)


class VerifyTests(OverlayTestCase):
    def test_fails_on_stale_generated_copy(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        (repo / "AGENTS.local.md").write_text("changed local\n", encoding="utf-8")
        proc = run_core(["verify"], worktree)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("is stale", proc.stdout)

    def test_fails_on_tracked_local_bridge(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "-f", "CLAUDE.local.md")
        run_git(repo, "commit", "-qm", "oops")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("CLAUDE.local.md is tracked", proc.stdout)

    def test_fails_on_codex_override_file(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        (repo / "AGENTS.override.md").write_text("override\n", encoding="utf-8")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("AGENTS.override.md replaces AGENTS.md", proc.stdout)

    def test_fails_on_nested_worktrees(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "worktree", "add", "-q", str(repo / "nested"))
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("worktrees must not nest", proc.stdout)

    @staticmethod
    def _write_claude_settings(repo: Path, data: dict, local: bool = False) -> None:
        d = repo / ".claude"
        d.mkdir(exist_ok=True)
        name = "settings.local.json" if local else "settings.json"
        (d / name).write_text(json.dumps(data), encoding="utf-8")

    def test_fails_on_disable_all_hooks(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        self._write_claude_settings(repo, {"disableAllHooks": True})
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("disableAllHooks is true", proc.stdout)

    def test_fails_when_claude_md_excludes_shared_bridge(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        self._write_claude_settings(repo, {"claudeMdExcludes": ["**/CLAUDE.md"]})
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("claudeMdExcludes matches", proc.stdout)
        self.assertIn("CLAUDE.md", proc.stdout)

    def test_fails_when_claude_md_excludes_local_bridge(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        self._write_claude_settings(
            repo, {"claudeMdExcludes": ["**/CLAUDE.local.md"]}, local=True
        )
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("claudeMdExcludes matches", proc.stdout)
        self.assertIn("CLAUDE.local.md", proc.stdout)

    def test_ok_when_claude_md_excludes_unrelated_path(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        self._write_claude_settings(
            repo, {"claudeMdExcludes": ["**/somewhere-else/CLAUDE.md"]}
        )
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 0, proc.stdout)

    def test_ignores_claude_settings_in_non_overlay_repo(self) -> None:
        # A plain repo with no shared/local source has no overlay Claude channel,
        # so its project-level disableAllHooks must not produce a finding.
        repo = self.base / "plain"
        repo.mkdir()
        run_git(repo, "init", "-q")
        self._write_claude_settings(repo, {"disableAllHooks": True})
        proc = run_core(["verify"], repo)
        self.assertNotIn("disableAllHooks", proc.stdout)

    def _user_home_with_claude_settings(self, data: dict) -> dict:
        home = self.base / "home"
        (home / ".claude").mkdir(parents=True)
        (home / ".claude" / "settings.json").write_text(json.dumps(data), encoding="utf-8")
        return {"HOME": str(home)}

    def test_fails_on_disable_all_hooks_in_user_settings(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        env = self._user_home_with_claude_settings({"disableAllHooks": True})
        proc = run_core(["verify"], repo, extra_env=env)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("disableAllHooks is true", proc.stdout)
        self.assertIn(str(self.base / "home"), proc.stdout)

    def test_local_settings_override_user_disable_all_hooks(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        env = self._user_home_with_claude_settings({"disableAllHooks": True})
        self._write_claude_settings(repo, {"disableAllHooks": False}, local=True)
        proc = run_core(["verify"], repo, extra_env=env)
        self.assertEqual(proc.returncode, 0, proc.stdout)

    def test_claude_md_excludes_merge_across_layers(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        env = self._user_home_with_claude_settings(
            {"claudeMdExcludes": ["**/CLAUDE.md"]}
        )
        self._write_claude_settings(
            repo, {"claudeMdExcludes": ["**/CLAUDE.local.md"]}, local=True
        )
        proc = run_core(["verify"], repo, extra_env=env)
        self.assertEqual(proc.returncode, 1)
        self.assertEqual(proc.stdout.count("claudeMdExcludes matches"), 2)
        self.assertIn("/CLAUDE.md;", proc.stdout)
        self.assertIn("/CLAUDE.local.md;", proc.stdout)

    def test_reads_symlinked_claude_settings(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        dotfiles = self.base / "dotfiles"
        dotfiles.mkdir()
        (dotfiles / "settings.json").write_text(
            json.dumps({"disableAllHooks": True}), encoding="utf-8"
        )
        (repo / ".claude").mkdir()
        (repo / ".claude" / "settings.json").symlink_to(dotfiles / "settings.json")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("disableAllHooks is true", proc.stdout)
        self.assertNotIn("could not read", proc.stdout)

    def test_claude_md_excludes_absolute_and_globstar_patterns(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        parent = str(repo.resolve().parent)
        cases = {
            f"{repo.resolve()}/CLAUDE.md": 1,
            f"{parent}/**": 1,
            f"{parent}/**/CLAUDE.md": 1,
            f"{parent}/*/CLAUDE.m?": 1,
            f"{parent}/**CLAUDE.md": 0,
            f"{parent}/*/*/CLAUDE.md": 0,
        }
        for pattern, expected in cases.items():
            self._write_claude_settings(repo, {"claudeMdExcludes": [pattern]})
            proc = run_core(["verify"], repo)
            self.assertEqual(proc.returncode, expected, f"{pattern}: {proc.stdout}")

    def test_warns_on_unevaluable_claude_md_excludes_pattern(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        self._write_claude_settings(
            repo, {"claudeMdExcludes": ["**/CLAUDE.{md,local.md}"]}
        )
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 0, proc.stdout)
        self.assertIn("WARN: claudeMdExcludes pattern(s)", proc.stdout)
        self.assertIn("does not evaluate", proc.stdout)

    def test_warns_outside_cli_version_window(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        stale_bin = write_cli_bin(
            self.base / "stale-bin", {**FAKE_CLI_SCRIPTS, "claude": "echo 9.9.9"}
        )
        proc = run_core(
            ["verify"],
            repo,
            extra_env={"PATH": f"{stale_bin}:{os.environ['PATH']}"},
        )
        self.assertEqual(proc.returncode, 0)
        self.assertIn("outside the live-verified window", proc.stdout)

    def test_accepts_current_live_verified_cli_versions(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        current_bin = write_cli_bin(
            self.base / "current-bin",
            {
                "claude": 'echo "2.1.252 (Claude Code)"',
                "codex": "echo codex-cli 0.152.0",
                "kiro-cli": (
                    'if [ "$1" = "settings" ] && [ "$2" = "list" ]; then\n'
                    '  printf \'%s\\n\' \'{"chat.disableInheritingDefaultResources": false}\'\n'
                    "  exit 0\n"
                    "fi\n"
                    "echo 2.20.2"
                ),
            },
        )
        proc = run_core(
            ["verify"],
            repo,
            extra_env={"PATH": f"{current_bin}:{os.environ['PATH']}"},
        )
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        self.assertNotIn("outside the live-verified window", proc.stdout)

    def codex_home_with(self, config: str) -> dict:
        home = self.base / "codex-home"
        home.mkdir(exist_ok=True)
        (home / "config.toml").write_text(config, encoding="utf-8")
        return {"CODEX_HOME": str(home)}

    def test_fails_on_codex_fallback_filenames(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        proc = run_core(
            ["verify"], repo, extra_env=self.codex_home_with('project_doc_fallback_filenames = ["X.md"]\n')
        )
        self.assertEqual(proc.returncode, 1)
        self.assertIn("project_doc_fallback_filenames", proc.stdout)

    def test_fails_on_codex_project_root_markers(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        proc = run_core(
            ["verify"], repo, extra_env=self.codex_home_with('project_root_markers = [".git"]\n')
        )
        self.assertEqual(proc.returncode, 1)
        self.assertIn("project_root_markers", proc.stdout)

    def test_fails_when_shared_rule_exceeds_codex_doc_cap(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        proc = run_core(
            ["verify"], repo, extra_env=self.codex_home_with("project_doc_max_bytes = 8\n")
        )
        self.assertEqual(proc.returncode, 1)
        self.assertIn("project_doc_max_bytes", proc.stdout)

    def test_warns_on_missing_codex_trust(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        proc = run_core(["verify"], repo, extra_env=self.codex_home_with(""))
        self.assertEqual(proc.returncode, 0)
        self.assertIn("no trusted entry", proc.stdout)

    def test_fails_when_worktree_lacks_shared_source(self) -> None:
        repo = self.base / "repo"
        repo.mkdir()
        run_git(repo, "init", "-q")
        (repo / "README.md").write_text("readme\n", encoding="utf-8")
        run_git(repo, "add", "README.md")
        run_git(repo, "commit", "-qm", "init")
        (repo / "AGENTS.md").write_text("untracked shared\n", encoding="utf-8")
        (repo / "AGENTS.local.md").write_text("local\n", encoding="utf-8")
        self.setup_repo(repo)
        worktree = self.add_worktree(repo)
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn(f"{worktree} has no AGENTS.md", proc.stdout)

    def test_fails_missing_shared_when_run_from_affected_worktree(self) -> None:
        repo = make_ignored_shared_repo(self.base)
        self.setup_repo(repo)
        worktree = self.add_worktree(repo)
        proc = run_core(["verify"], worktree)
        self.assertEqual(proc.returncode, 1)
        self.assertIn(f"{worktree} has no AGENTS.md", proc.stdout)

    def test_fails_on_kiro_inheritance_true(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        true_bin = write_cli_bin(
            self.base / "kiro-true-bin",
            {
                **FAKE_CLI_SCRIPTS,
                "kiro-cli": (
                    'if [ "$1" = "settings" ] && [ "$2" = "list" ]; then\n'
                    '  printf \'%s\\n\' \'{"chat.disableInheritingDefaultResources": true}\'\n'
                    "  exit 0\nfi\necho 2.15.1"
                ),
            },
        )
        proc = run_core(
            ["verify"], repo, extra_env={"PATH": f"{true_bin}:{os.environ['PATH']}"}
        )
        self.assertEqual(proc.returncode, 1)
        self.assertIn("FAIL: kiro:", proc.stdout)

    def test_fails_on_invalid_shared_source_in_other_worktree(self) -> None:
        repo = make_ignored_shared_repo(self.base)
        self.setup_repo(repo)
        worktree = self.add_worktree(repo)
        (worktree / "AGENTS.md").symlink_to(repo / "AGENTS.md")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn(f"{worktree / 'AGENTS.md'} is a symlink", proc.stdout)

    def test_fails_on_local_bridge_tracked_in_other_worktree(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        run_git(worktree, "add", "-f", "CLAUDE.local.md")
        run_git(worktree, "commit", "-qm", "oops")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn(f"CLAUDE.local.md is tracked in {worktree}", proc.stdout)

    def test_fails_on_tracked_local_even_without_primary_source(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        (repo / "AGENTS.local.md").unlink()
        (worktree / "AGENTS.local.md").write_text("rogue local\n", encoding="utf-8")
        run_git(worktree, "add", "-f", "AGENTS.local.md")
        run_git(worktree, "commit", "-qm", "oops")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn(f"AGENTS.local.md is tracked in {worktree}", proc.stdout)

    def test_fails_on_override_in_other_worktree(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        (worktree / "AGENTS.override.md").write_text("override\n", encoding="utf-8")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn(f"{worktree / 'AGENTS.override.md'} replaces AGENTS.md", proc.stdout)

    def test_fails_when_other_worktree_shared_exceeds_claude_budget(self) -> None:
        repo = make_ignored_shared_repo(self.base)
        self.setup_repo(repo)
        worktree = self.add_worktree(repo)
        (worktree / "AGENTS.md").write_text("z" * 10500 + "\n", encoding="utf-8")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("Claude subagent hook budget", proc.stdout)
        self.assertIn(str(worktree / "AGENTS.md"), proc.stdout)

    def test_fails_on_foreign_steering_in_other_worktree(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        steering = worktree / ".kiro/steering/agents-local-overlay.md"
        steering.parent.mkdir(parents=True)
        steering.write_text("my own steering\n", encoding="utf-8")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn(f"{steering} exists but is not overlay-generated", proc.stdout)

    def test_fails_on_worktree_only_local_source(self) -> None:
        repo = make_repo(self.base, local=False)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        (worktree / "AGENTS.local.md").write_text("stranded local\n", encoding="utf-8")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("local source lives in the primary worktree only", proc.stdout)

    def test_fails_on_stray_local_source_in_worktree(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        (worktree / "AGENTS.local.md").write_text("stray\n", encoding="utf-8")
        proc = run_core(["verify"], worktree)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("local source lives in the primary worktree only", proc.stdout)

    def test_fails_when_combined_rules_exceed_claude_budget(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        (repo / "AGENTS.md").write_text("x" * 9000 + "\n", encoding="utf-8")
        (repo / "AGENTS.local.md").write_text("y" * 2000 + "\n", encoding="utf-8")
        proc = run_core(["verify"], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("Claude subagent hook budget", proc.stdout)


class ClaudeSessionHookTests(OverlayTestCase):
    def test_silent_when_healthy(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        proc = run_core(CLAUDE_SESSION, repo, stdin=hook_stdin(repo))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_refreshes_stale_copy_in_worktree(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        (repo / "AGENTS.local.md").write_text("fresh local Z\n", encoding="utf-8")
        proc = run_core(CLAUDE_SESSION, worktree, stdin=hook_stdin(worktree))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")
        self.assertIn("fresh local Z", (worktree / "CLAUDE.local.md").read_text(encoding="utf-8"))

    def test_removes_generated_copy_when_source_is_gone(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        self.setup_repo(worktree)
        (repo / "AGENTS.local.md").unlink()
        proc = run_core(CLAUDE_SESSION, worktree, stdin=hook_stdin(worktree))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertFalse((worktree / "CLAUDE.local.md").exists())

    def test_notice_when_native_channel_disabled(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        proc = run_core(
            CLAUDE_SESSION,
            repo,
            stdin=hook_stdin(repo),
            extra_env={"CLAUDE_CODE_DISABLE_CLAUDE_MDS": "1"},
        )
        self.assertIn("CLAUDE_CODE_DISABLE_CLAUDE_MDS", hook_context(proc))

    def test_notice_when_shared_bridge_missing(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        (repo / "CLAUDE.md").unlink()
        proc = run_core(CLAUDE_SESSION, repo, stdin=hook_stdin(repo))
        self.assertIn("CLAUDE.md bridge is missing", hook_context(proc))

    def test_notice_on_foreign_copy_in_worktree(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        (worktree / "CLAUDE.local.md").write_text("my own notes\n", encoding="utf-8")
        proc = run_core(CLAUDE_SESSION, worktree, stdin=hook_stdin(worktree))
        self.assertIn("not overlay-generated", hook_context(proc))
        self.assertEqual(
            (worktree / "CLAUDE.local.md").read_text(encoding="utf-8"), "my own notes\n"
        )

    def test_silent_outside_git(self) -> None:
        outside = self.base / "plain"
        outside.mkdir()
        proc = run_core(CLAUDE_SESSION, outside, stdin=hook_stdin(outside))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_silent_in_non_overlay_repo(self) -> None:
        repo = make_repo(self.base, local=False)
        proc = run_core(CLAUDE_SESSION, repo, stdin=hook_stdin(repo))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")


class ClaudeSubagentHookTests(OverlayTestCase):
    def test_injects_shared_and_local(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(CLAUDE_SUBAGENT, repo, stdin=hook_stdin(repo, agent_type="Explore"))
        context = hook_context(proc)
        self.assertIn("shared rule X", context)
        self.assertIn("local rule Y", context)

    def test_plan_injects_like_explore(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(CLAUDE_SUBAGENT, repo, stdin=hook_stdin(repo, agent_type="Plan"))
        context = hook_context(proc)
        self.assertIn("shared rule X", context)
        self.assertIn("local rule Y", context)

    def test_fork_is_silent(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(CLAUDE_SUBAGENT, repo, stdin=hook_stdin(repo, agent_type="fork"))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_general_purpose_is_silent(self) -> None:
        # general-purpose receives native project + local memory, so injecting
        # would duplicate the rules.
        repo = make_repo(self.base)
        proc = run_core(
            CLAUDE_SUBAGENT, repo, stdin=hook_stdin(repo, agent_type="general-purpose")
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_custom_subagent_is_silent(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(
            CLAUDE_SUBAGENT, repo, stdin=hook_stdin(repo, agent_type="my-custom-agent")
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_missing_agent_type_emits_notice_only(self) -> None:
        repo = make_repo(self.base)
        for stdin in (hook_stdin(repo), hook_stdin(repo, agent_type=["Explore"])):
            proc = run_core(CLAUDE_SUBAGENT, repo, stdin=stdin)
            self.assertEqual(proc.returncode, 0, proc.stderr)
            context = hook_context(proc)
            self.assertIn("no string agent_type", context)
            self.assertNotIn("shared rule X", context)

    def test_over_cap_replaces_body_with_notice(self) -> None:
        repo = make_repo(self.base)
        (repo / "AGENTS.md").write_text("x" * 11000 + "\n", encoding="utf-8")
        proc = run_core(CLAUDE_SUBAGENT, repo, stdin=hook_stdin(repo, agent_type="Explore"))
        context = hook_context(proc)
        self.assertIn("Rules not injected", context)
        self.assertNotIn("xxxx", context)

    def test_notices_missing_shared_in_worktree(self) -> None:
        repo = make_ignored_shared_repo(self.base)
        worktree = self.add_worktree(repo)
        proc = run_core(CLAUDE_SUBAGENT, worktree, stdin=hook_stdin(worktree, agent_type="Explore"))
        context = hook_context(proc)
        self.assertIn("has no AGENTS.md", context)
        self.assertIn("local rule Y", context)

    def test_invalid_local_keeps_healthy_shared(self) -> None:
        repo = make_repo(self.base)
        (repo / "AGENTS.local.md").unlink()
        (repo / "AGENTS.local.md").symlink_to(repo / "AGENTS.md")
        proc = run_core(CLAUDE_SUBAGENT, repo, stdin=hook_stdin(repo, agent_type="Explore"))
        context = hook_context(proc)
        self.assertIn("is a symlink", context)
        self.assertIn("shared rule X", context)


class CodexHookTests(OverlayTestCase):
    def test_injects_local_only(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(CODEX_SESSION, repo, stdin=hook_stdin(repo))
        context = hook_context(proc)
        self.assertIn("local rule Y", context)
        self.assertNotIn("shared rule X", context)

    def test_silent_without_local_source(self) -> None:
        repo = make_repo(self.base, local=False)
        proc = run_core(CODEX_SESSION, repo, stdin=hook_stdin(repo))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_override_notice_and_local_still_injected(self) -> None:
        repo = make_repo(self.base)
        (repo / "AGENTS.override.md").write_text("override\n", encoding="utf-8")
        proc = run_core(CODEX_SESSION, repo, stdin=hook_stdin(repo))
        context = hook_context(proc)
        self.assertIn("AGENTS.override.md replaces AGENTS.md", context)
        self.assertIn("local rule Y", context)

    def test_bad_stdin_fails_loudly(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(CODEX_SESSION, repo, stdin="not json")
        self.assertEqual(proc.returncode, 1)
        self.assertIn("JSON hook input", proc.stderr)

    def test_silent_with_override_but_no_local(self) -> None:
        repo = make_repo(self.base, local=False)
        (repo / "AGENTS.override.md").write_text("override\n", encoding="utf-8")
        proc = run_core(CODEX_SESSION, repo, stdin=hook_stdin(repo))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_notices_missing_shared_in_worktree(self) -> None:
        repo = make_ignored_shared_repo(self.base)
        worktree = self.add_worktree(repo)
        proc = run_core(CODEX_SESSION, worktree, stdin=hook_stdin(worktree))
        context = hook_context(proc)
        self.assertIn("has no AGENTS.md", context)
        self.assertIn("local rule Y", context)

    def test_subagent_policy_injects_local(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(CODEX_SUBAGENT, repo, stdin=hook_stdin(repo))
        self.assertIn("local rule Y", hook_context(proc))

    def test_notices_worktree_only_local_source(self) -> None:
        repo = make_repo(self.base, local=False)
        worktree = self.add_worktree(repo)
        (worktree / "AGENTS.local.md").write_text("stranded local\n", encoding="utf-8")
        proc = run_core(CODEX_SESSION, worktree, stdin=hook_stdin(worktree))
        context = hook_context(proc)
        self.assertIn("is not read", context)
        self.assertNotIn("stranded local", context)

    def test_stray_local_notice_includes_broken_shared(self) -> None:
        repo = make_repo(self.base, local=False)
        worktree = self.add_worktree(repo)
        (worktree / "AGENTS.local.md").write_text("stranded local\n", encoding="utf-8")
        (worktree / "AGENTS.md").unlink()
        (worktree / "AGENTS.md").symlink_to(repo / "AGENTS.md")
        proc = run_core(CODEX_SESSION, worktree, stdin=hook_stdin(worktree))
        context = hook_context(proc)
        self.assertIn("is not read", context)
        self.assertIn("is a symlink", context)
        self.assertNotIn("stranded local", context)

    def test_notice_on_invalid_shared_source(self) -> None:
        repo = make_repo(self.base)
        (repo / "AGENTS.md").unlink()
        (repo / "AGENTS.md").symlink_to(repo / "AGENTS.local.md")
        proc = run_core(CODEX_SESSION, repo, stdin=hook_stdin(repo))
        context = hook_context(proc)
        self.assertIn("is a symlink", context)
        self.assertIn("local rule Y", context)

    def test_no_override_notice_for_primary_only_override_in_linked(self) -> None:
        repo = make_repo(self.base)
        worktree = self.add_worktree(repo)
        (repo / "AGENTS.override.md").write_text("override\n", encoding="utf-8")
        proc = run_core(CODEX_SESSION, worktree, stdin=hook_stdin(worktree))
        context = hook_context(proc)
        self.assertNotIn("AGENTS.override.md", context)
        self.assertIn("local rule Y", context)

    def test_worktree_uses_primary_local_source(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        run_git(repo, "add", "CLAUDE.md", ".gitignore")
        run_git(repo, "commit", "-qm", "bridge")
        worktree = self.add_worktree(repo)
        proc = run_core(CODEX_SESSION, worktree, stdin=hook_stdin(worktree))
        self.assertIn("local rule Y", hook_context(proc))

    def test_over_cap_replaces_body_with_notice(self) -> None:
        repo = make_repo(self.base)
        (repo / "AGENTS.local.md").write_text("y" * 40000 + "\n", encoding="utf-8")
        proc = run_core(CODEX_SESSION, repo, stdin=hook_stdin(repo))
        context = hook_context(proc)
        self.assertIn("Rules not injected", context)
        self.assertNotIn("yyyy", context)


class KiroBodyTests(OverlayTestCase):
    def test_prints_local_body(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(["kiro-body", str(repo)], repo)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("local rule Y", proc.stdout)
        self.assertNotIn("shared rule X", proc.stdout)

    def test_empty_without_local_source(self) -> None:
        repo = make_repo(self.base, local=False)
        proc = run_core(["kiro-body", str(repo)], repo)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_aborts_when_inheritance_setting_unfixable(self) -> None:
        repo = make_repo(self.base)
        broken_bin = write_cli_bin(
            self.base / "broken-bin",
            {
                **FAKE_CLI_SCRIPTS,
                "kiro-cli": (
                    'if [ "$1" = "settings" ] && [ "$2" = "list" ]; then\n'
                    "  printf '{}\\n'\n  exit 0\nfi\necho 2.15.1"
                ),
            },
        )
        proc = run_core(
            ["kiro-body", str(repo)],
            repo,
            extra_env={"PATH": f"{broken_bin}:{os.environ['PATH']}"},
        )
        self.assertEqual(proc.returncode, 1)
        self.assertIn("chat.disableInheritingDefaultResources", proc.stderr)

    def test_autofixes_missing_inheritance_setting(self) -> None:
        repo = make_repo(self.base)
        state = self.base / "kiro-state"
        fix_bin = write_cli_bin(
            self.base / "fix-bin",
            {
                **FAKE_CLI_SCRIPTS,
                "kiro-cli": (
                    f'STATE="{state}"\n'
                    'if [ "$1" = "settings" ] && [ "$2" = "list" ]; then\n'
                    '  if [ -f "$STATE" ]; then\n'
                    '    printf \'%s\\n\' \'{"chat.disableInheritingDefaultResources": false}\'\n'
                    "  else\n    printf '{}\\n'\n  fi\n  exit 0\nfi\n"
                    'if [ "$1" = "settings" ] && [ "$2" = "chat.disableInheritingDefaultResources" ]; then\n'
                    '  : > "$STATE"\n  exit 0\nfi\necho 2.15.1'
                ),
            },
        )
        proc = run_core(
            ["kiro-body", str(repo)],
            repo,
            extra_env={"PATH": f"{fix_bin}:{os.environ['PATH']}"},
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("local rule Y", proc.stdout)
        self.assertTrue(state.exists())

    def test_aborts_on_override_file(self) -> None:
        repo = make_repo(self.base)
        (repo / "AGENTS.override.md").write_text("override\n", encoding="utf-8")
        proc = run_core(["kiro-body", str(repo)], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("AGENTS.override.md", proc.stderr)

    def test_aborts_on_invalid_shared_source(self) -> None:
        repo = make_repo(self.base)
        (repo / "AGENTS.md").unlink()
        (repo / "AGENTS.md").symlink_to(repo / "AGENTS.local.md")
        proc = run_core(["kiro-body", str(repo)], repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("is a symlink", proc.stderr)


class KiroLauncherTests(OverlayTestCase):
    def run_launcher(self, repo: Path, extra_env: dict | None = None) -> subprocess.CompletedProcess:
        launcher_bin = write_cli_bin(
            self.base / "launcher-bin", {**FAKE_CLI_SCRIPTS, "kiro-cli": (
                'if [ "$1" = "settings" ] && [ "$2" = "list" ]; then\n'
                '  printf \'%s\\n\' \'{"chat.disableInheritingDefaultResources": false}\'\n'
                "  exit 0\nfi\necho KIRO-RUN \"$@\""
            )},
        )
        env = {"PATH": f"{launcher_bin}:{os.environ['PATH']}"}
        if extra_env:
            env.update(extra_env)
        return subprocess.run(
            [sys.executable, str(KIRO)],
            cwd=str(repo),
            capture_output=True,
            text=True,
            env=isolated_env(env),
            timeout=60,
        )

    def test_writes_steering_and_execs_kiro(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        proc = self.run_launcher(repo)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("KIRO-RUN --v3", proc.stdout)
        steering = repo / ".kiro/steering/agents-local-overlay.md"
        text = steering.read_text(encoding="utf-8")
        self.assertTrue(text.startswith(KIRO_OWNER + "\n"))
        self.assertIn("local rule Y", text)
        self.assertNotIn("shared rule X", text)

    def test_removes_steering_when_local_source_missing(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        self.run_launcher(repo)
        (repo / "AGENTS.local.md").unlink()
        proc = self.run_launcher(repo)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertFalse((repo / ".kiro/steering/agents-local-overlay.md").exists())

    def test_aborts_on_tracked_steering(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        steering = repo / ".kiro/steering/agents-local-overlay.md"
        steering.parent.mkdir(parents=True, exist_ok=True)
        steering.write_text(KIRO_OWNER + "\n\nbody\n", encoding="utf-8")
        run_git(repo, "add", "-f", str(steering))
        proc = self.run_launcher(repo)
        self.assertEqual(proc.returncode, 1)
        self.assertIn("tracked", proc.stderr)


class WorktreeCreateTests(OverlayTestCase):
    def test_creates_worktree_with_generated_copy(self) -> None:
        repo = make_repo(self.base)
        self.setup_repo(repo)
        home = self.base / "home"
        home.mkdir()
        proc = run_core(
            ["claude-worktree-create"],
            repo,
            stdin=hook_stdin(repo, name="feat1"),
            extra_env={"HOME": str(home)},
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        target = Path(proc.stdout.strip())
        self.assertTrue(target.is_dir())
        self.assertTrue(str(target).startswith(str(home)))
        copy = target / "CLAUDE.local.md"
        self.assertTrue(copy.exists())
        self.assertIn("local rule Y", copy.read_text(encoding="utf-8"))

    def test_fails_on_invalid_local_source(self) -> None:
        repo = make_repo(self.base)
        (repo / "AGENTS.local.md").unlink()
        (repo / "AGENTS.local.md").symlink_to(repo / "AGENTS.md")
        home = self.base / "home"
        home.mkdir()
        proc = run_core(
            ["claude-worktree-create"],
            repo,
            stdin=hook_stdin(repo, name="feat1"),
            extra_env={"HOME": str(home)},
        )
        self.assertEqual(proc.returncode, 1)
        self.assertIn("symlink", proc.stderr)
        self.assertEqual(proc.stdout, "")

    def test_rejects_unsafe_name(self) -> None:
        repo = make_repo(self.base)
        proc = run_core(
            ["claude-worktree-create"],
            repo,
            stdin=hook_stdin(repo, name="../evil"),
            extra_env={"HOME": str(self.base)},
        )
        self.assertEqual(proc.returncode, 1)
        self.assertIn("simple slug", proc.stderr)


class BareRepoTests(OverlayTestCase):
    def test_bare_primary_uses_metadata_dir_local_source(self) -> None:
        bare = self.base / "bare.git"
        subprocess.run(
            ["git", "init", "-q", "--bare", str(bare)],
            check=True,
            capture_output=True,
            env=isolated_env(),
        )
        seed = make_repo(self.base, name="seed")
        run_git(seed, "push", "-q", str(bare), "HEAD:main")
        checkout = self.base / "co"
        subprocess.run(
            ["git", "-C", str(bare), "worktree", "add", "-q", str(checkout), "main"],
            check=True,
            capture_output=True,
            env=isolated_env(),
        )
        (bare / "AGENTS.local.md").write_text("bare local B\n", encoding="utf-8")
        proc = run_core(CODEX_SESSION, checkout, stdin=hook_stdin(checkout))
        self.assertIn("bare local B", hook_context(proc))
        setup = run_core(["setup"], checkout)
        self.assertEqual(setup.returncode, 0, setup.stdout + setup.stderr)
        copy = checkout / "CLAUDE.local.md"
        self.assertTrue(copy.exists())
        text = copy.read_text(encoding="utf-8")
        self.assertTrue(text.startswith(GENERATED_OWNER + "\n"))
        self.assertIn("bare local B", text)


if __name__ == "__main__":
    unittest.main()
