#!/usr/bin/env python3
"""agents-local-overlay v2 core.

One delivery channel per logical rule source per CLI context, fixed statically:

- Claude main session: AGENTS.md via the committed CLAUDE.md bridge (native);
  AGENTS.local.md via CLAUDE.local.md (primary worktree: one-line bridge
  import; other worktrees: generated content copy refreshed by the
  SessionStart hook before native memory is read).
- Claude subagent: the built-in Explore and Plan subagents start without native
  memory, so the SubagentStart hook injects the shared+local snapshot for them
  only; every other subagent inherits the main session's project+local memory.
- Codex: AGENTS.md via the native project doc loader; AGENTS.local.md via the
  SessionStart/SubagentStart hook.
- Kiro: AGENTS.md via the native default-resource channel; AGENTS.local.md via
  the generated steering document (kiro-cli-overlay launcher).

The hook never infers what a native loader read and never moves a source
between channels. When a channel precondition is not met, the hook emits a
notice instead of rules, and `verify` fails.
"""
from __future__ import annotations

import json
import os
import re
import hashlib
import shutil
import stat
import subprocess
import sys
import tempfile
from dataclasses import dataclass, replace
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 unsupported
    tomllib = None

SHARED_RULE = "AGENTS.md"
LOCAL_RULE = "AGENTS.local.md"
CODEX_OVERRIDE = "AGENTS.override.md"
CLAUDE_SHARED_BRIDGE = "CLAUDE.md"
CLAUDE_LOCAL_BRIDGE = "CLAUDE.local.md"
SHARED_BRIDGE_MARKER = "@AGENTS.md"
LOCAL_BRIDGE_MARKER = "@AGENTS.local.md"
KIRO_STEERING_REL = ".kiro/steering/agents-local-overlay.md"
KIRO_STEERING_OWNER = "<!-- generated by agents-local-overlay; do not edit -->"

GENERATED_LOCAL_OWNER = (
    "<!-- generated by agents-local-overlay from the primary AGENTS.local.md; do not edit -->"
)

NOTICE_PREFIX = "[agents-local-overlay] "
# Live-verified (Claude 2.1.252): only built-in Explore and Plan start without
# native CLAUDE.md memory; every other subagent inherits it, so injecting there
# duplicates the rules. A custom agent named Explore/Plan is indistinguishable.
SUBAGENTS_WITHOUT_NATIVE_MEMORY = frozenset({"Explore", "Plan"})
CLAUDE_MAX_CHARS = 10000
CODEX_MAX_CHARS = 32768
KIRO_MAX_CHARS = 32768
CODEX_DEFAULT_PROJECT_DOC_MAX_BYTES = 32768

CLAUDE_WORKTREE_DIR_ENV = "AGENTS_OVERLAY_CLAUDE_WORKTREE_DIR"
CLAUDE_WORKTREE_BASE_ENV = "AGENTS_OVERLAY_CLAUDE_WORKTREE_BASE_REF"

KIRO_INHERITANCE_SETTING = "chat.disableInheritingDefaultResources"
KIRO_FALSE_REMEDIATION = (
    f"run: kiro-cli settings {KIRO_INHERITANCE_SETTING} false"
)
KIRO_VERIFY_REFUSAL = f"could not verify Kiro settings; {KIRO_FALSE_REMEDIATION}"

CLI_VERSION_WINDOWS = {
    "claude": ((2, 1, 232), (2, 1, 252)),
    "codex": ((0, 147, 0), (0, 152, 0)),
    "kiro-cli": ((2, 15, 1), (2, 20, 2)),
}


class OverlayError(Exception):
    pass


class QuietExit(Exception):
    pass


def fail(message: str, code: int = 1) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(code)


def usage() -> str:
    return (
        "usage: agents-overlay-context <command>\n"
        "  json <event> <shared-native> <local-native> <project-dir> <policy>\n"
        "      hook mode; policies: claude-session, claude-subagent,\n"
        "      codex-session, codex-subagent\n"
        "  kiro-body <worktree-top>   print the Kiro steering body\n"
        "  setup [dir]                create bridges, copies, ignore patterns\n"
        "  verify [dir]               check the repo against the contract\n"
        "  claude-worktree-create     WorktreeCreate hook\n"
        "  claude-worktree-remove     WorktreeRemove hook\n"
    )


# --- process helpers ---------------------------------------------------------


def run_git(
    cwd: Path, args: Sequence[str], check: bool = True
) -> subprocess.CompletedProcess[bytes]:
    if not cwd.is_dir():
        raise OverlayError(f"cannot run git in {cwd}: directory does not exist")
    try:
        proc = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
    except FileNotFoundError:
        raise OverlayError("git is required")
    if check and proc.returncode != 0:
        detail = proc.stderr.decode("utf-8", "replace").strip()
        suffix = f": {detail}" if detail else ""
        raise OverlayError(f"git {' '.join(args)} failed{suffix}")
    return proc


def one_line_stdout(proc: subprocess.CompletedProcess[bytes], label: str) -> Path:
    data = proc.stdout
    if not data.endswith(b"\n"):
        raise OverlayError(f"{label} did not return one newline-terminated path")
    try:
        return Path(data[:-1].decode("utf-8"))
    except UnicodeDecodeError as exc:
        raise OverlayError(f"{label} returned a non-UTF-8 path") from exc


# --- repo context ------------------------------------------------------------


@dataclass(frozen=True)
class RepoContext:
    start: Path
    top: Path
    root: Path
    common: Path
    worktrees: Tuple[Path, ...]

    @property
    def root_is_bare(self) -> bool:
        try:
            if self.root == self.common or os.path.samefile(self.root, self.common):
                return True
        except OSError:
            pass
        return False

    @property
    def checkout_worktrees(self) -> Tuple[Path, ...]:
        if self.root_is_bare:
            return tuple(w for w in self.worktrees if w != self.root)
        return self.worktrees

    @property
    def copy_worktrees(self) -> Tuple[Path, ...]:
        """Worktrees whose CLAUDE.local.md is a generated content copy."""
        return tuple(w for w in self.checkout_worktrees if w != self.root)


def resolve_context(project_dir: str, require_git: bool = False) -> RepoContext:
    try:
        start = Path(project_dir).resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise OverlayError(f"cannot enter project directory: {project_dir}") from exc
    if not start.is_dir():
        raise OverlayError(f"project directory is not a directory: {project_dir}")
    top_proc = run_git(
        start, ["rev-parse", "--path-format=absolute", "--show-toplevel"], check=False
    )
    if top_proc.returncode != 0:
        if require_git:
            raise OverlayError("run inside a Git worktree")
        raise QuietExit()
    top = one_line_stdout(top_proc, "git rev-parse --show-toplevel")
    common = one_line_stdout(
        run_git(top, ["rev-parse", "--path-format=absolute", "--git-common-dir"]),
        "git rev-parse --git-common-dir",
    )
    records = run_git(top, ["worktree", "list", "--porcelain", "-z"]).stdout.split(b"\0")
    if not records or not records[0].startswith(b"worktree "):
        raise OverlayError("could not resolve primary worktree")
    worktrees: List[Path] = []
    for record in records:
        if not record.startswith(b"worktree "):
            continue
        try:
            worktrees.append(Path(record[len(b"worktree ") :].decode("utf-8")))
        except UnicodeDecodeError as exc:
            raise OverlayError("worktree path is not UTF-8") from exc
    root = worktrees[0]
    if not root.is_absolute():
        raise OverlayError("primary worktree path is not absolute")
    if not root.is_dir():
        raise OverlayError("primary worktree path is not a directory")
    # /tmp vs /private/tmp style aliases break membership/equality checks, so
    # every context path is stored fully resolved.
    return RepoContext(
        start=resolved_or_self(start),
        top=resolved_or_self(top),
        root=resolved_or_self(root),
        common=resolved_or_self(common),
        worktrees=tuple(resolved_or_self(w) for w in worktrees),
    )


def path_exists(path: Path) -> bool:
    return os.path.lexists(path)


def resolved_or_self(path: Path) -> Path:
    try:
        return path.resolve(strict=False)
    except (OSError, RuntimeError):
        return path


def path_is_within(path: Path, ancestor: Path) -> bool:
    try:
        resolved_or_self(path).relative_to(resolved_or_self(ancestor))
    except ValueError:
        return False
    return True


def worktrees_nest(a: Path, b: Path) -> bool:
    return a != b and (path_is_within(a, b) or path_is_within(b, a))


def worktree_nesting_problems(ctx: RepoContext) -> List[str]:
    problems: List[str] = []
    seen = ctx.worktrees
    for i, outer in enumerate(seen):
        for inner in seen[i + 1 :]:
            if worktrees_nest(outer, inner):
                problems.append(
                    f"worktrees must not nest: {outer} and {inner}; "
                    "move one outside the other"
                )
    return problems


def drop_missing_worktrees(ctx: RepoContext, problems: List[str]) -> RepoContext:
    """Report registered worktrees whose directory is gone and exclude them.

    The primary is always present because resolve_context requires it.
    """
    present = []
    for worktree in ctx.worktrees:
        if worktree.is_dir():
            present.append(worktree)
            continue
        problems.append(
            f"{worktree} is registered as a worktree but does not exist; run "
            "git worktree prune (deleted) or git worktree repair (moved)"
        )
    if len(present) == len(ctx.worktrees):
        return ctx
    return replace(ctx, worktrees=tuple(present))


def worktree_topology_notices(ctx: RepoContext) -> List[str]:
    """Delivery problems caused by where this checkout sits, not by its files."""
    notices: List[str] = []
    if ctx.top not in ctx.worktrees:
        notices.append(
            f"Rules not delivered: {ctx.top} is not in git worktree list (moved "
            f"without git worktree move?); its {CLAUDE_LOCAL_BRIDGE} copy is not "
            "refreshed — run git worktree repair, then agents-overlay-context setup"
        )
    for other in ctx.worktrees:
        if worktrees_nest(ctx.top, other):
            notices.append(
                f"Rules may be duplicated: {ctx.top} nests with worktree {other}; "
                "Claude loads rule files from both directories — move one outside "
                "the other"
            )
    return notices


# --- rule file IO ------------------------------------------------------------


def rule_refusal_detail(path: Path) -> str:
    try:
        mode = path.lstat().st_mode
    except OSError as exc:
        return f"could not inspect rule file {path}: {exc}"
    if stat.S_ISLNK(mode):
        return f"{path} is a symlink; symlinked rule files are never read as rules"
    if not stat.S_ISREG(mode):
        return f"{path} is not a regular file"
    if not os.access(path, os.R_OK):
        return f"{path} is not readable"
    return f"{path} is not a readable regular file"


def read_regular_file_bytes(path: Path) -> bytes:
    nofollow = getattr(os, "O_NOFOLLOW", 0)
    if nofollow == 0:
        try:
            mode = path.lstat().st_mode
        except OSError as exc:
            raise OverlayError(f"could not inspect rule file {path}: {exc}") from exc
        if stat.S_ISLNK(mode):
            raise OverlayError(rule_refusal_detail(path))
    try:
        fd = os.open(path, os.O_RDONLY | nofollow)
    except OSError as exc:
        raise OverlayError(rule_refusal_detail(path)) from exc
    try:
        st = os.fstat(fd)
        if not stat.S_ISREG(st.st_mode):
            raise OverlayError(f"{path} is not a regular file")
        chunks = []
        while True:
            chunk = os.read(fd, 65536)
            if not chunk:
                break
            chunks.append(chunk)
        return b"".join(chunks)
    finally:
        os.close(fd)


def decode_rule(data: bytes, desc: str) -> str:
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise OverlayError(f"rule file is not UTF-8: {desc}") from exc
    if "\0" in text:
        raise OverlayError(f"rule file contains NUL: {desc}")
    return text.rstrip("\n")


def read_rule(path: Path) -> str:
    return decode_rule(read_regular_file_bytes(path), str(path))


def atomic_write(path: Path, data: str) -> None:
    file_mode = 0o644
    if path_exists(path):
        try:
            mode = path.lstat().st_mode
        except OSError as exc:
            raise OverlayError(f"could not inspect {path}: {exc}") from exc
        if stat.S_ISLNK(mode) or not stat.S_ISREG(mode):
            raise OverlayError(f"{path} is not a regular file")
        file_mode = stat.S_IMODE(mode) & 0o777
    tmp_path: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as tmp:
            tmp_path = Path(tmp.name)
            tmp.write(data)
        tmp_path.chmod(file_mode)
        os.replace(tmp_path, path)
        tmp_path = None
    except OSError as exc:
        raise OverlayError(f"could not write {path}: {exc}") from exc
    finally:
        if tmp_path is not None:
            try:
                tmp_path.unlink()
            except OSError:
                pass


# --- bridges and generated copies -------------------------------------------


def bridge_is_exact(data: bytes, marker: str) -> bool:
    expected = marker.encode("utf-8")
    return data == expected or data == expected + b"\n"


def bridge_is_normalizable(data: bytes, marker: str) -> bool:
    if bridge_is_exact(data, marker):
        return True
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return False
    if "\0" in text:
        return False
    if text.startswith("﻿"):
        text = text[1:]
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    content = [line.rstrip() for line in text.split("\n") if line.strip()]
    if len(content) != 1:
        return False
    if content[0] != content[0].lstrip():
        return False
    dotted = "@./" + marker[1:]
    return content[0] in (marker, dotted)


@dataclass(frozen=True)
class BridgeState:
    exists: bool
    exact: bool
    normalizable: bool


def bridge_state(path: Path, marker: str) -> BridgeState:
    if not path_exists(path):
        return BridgeState(exists=False, exact=False, normalizable=False)
    data = read_regular_file_bytes(path)
    exact = bridge_is_exact(data, marker)
    return BridgeState(
        exists=True,
        exact=exact,
        normalizable=exact or bridge_is_normalizable(data, marker),
    )


def generated_copy_text(local_text: str) -> str:
    return GENERATED_LOCAL_OWNER + "\n\n" + local_text + "\n"


@dataclass(frozen=True)
class CopyState:
    exists: bool
    owned: bool
    fresh: bool


def generated_copy_state(path: Path, local_text: Optional[str]) -> CopyState:
    if not path_exists(path):
        return CopyState(exists=False, owned=False, fresh=False)
    data = read_regular_file_bytes(path)
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return CopyState(exists=True, owned=False, fresh=False)
    owned = text.split("\n", 1)[0] == GENERATED_LOCAL_OWNER
    fresh = owned and local_text is not None and text == generated_copy_text(local_text)
    return CopyState(exists=True, owned=owned, fresh=fresh)


def local_source_path(ctx: RepoContext) -> Path:
    return ctx.root / LOCAL_RULE


def shared_source_path(ctx: RepoContext) -> Path:
    return ctx.top / SHARED_RULE


def overlay_opted_in(ctx: RepoContext) -> bool:
    if path_exists(local_source_path(ctx)):
        return True
    if ctx.top != ctx.root and path_exists(ctx.top / LOCAL_RULE):
        return True
    for worktree in ctx.copy_worktrees:
        copy = worktree / CLAUDE_LOCAL_BRIDGE
        if path_exists(copy):
            try:
                if generated_copy_state(copy, None).owned:
                    return True
            except OverlayError:
                continue
    if not ctx.root_is_bare:
        bridge = ctx.root / CLAUDE_LOCAL_BRIDGE
        if path_exists(bridge):
            try:
                if bridge_state(bridge, LOCAL_BRIDGE_MARKER).normalizable:
                    return True
            except OverlayError:
                pass
    return False


def refresh_generated_copy(
    worktree: Path, local_text: Optional[str], notices: List[str]
) -> bool:
    """Bring one worktree's generated CLAUDE.local.md in line with the source.

    Returns True when the file was created, rewritten, or removed.
    """
    target = worktree / CLAUDE_LOCAL_BRIDGE
    try:
        state = generated_copy_state(target, local_text)
    except OverlayError as exc:
        notices.append(f"Rules not delivered: {exc}")
        return False
    if local_text is None:
        if state.exists and state.owned:
            try:
                os.remove(target)
            except OSError as exc:
                notices.append(f"Rules not delivered: could not remove stale {target}: {exc}")
                return False
            return True
        if state.exists and not state.owned:
            notices.append(
                f"Rules not delivered: {target} exists but the primary {LOCAL_RULE} "
                "source is missing; move its content to the primary source"
            )
        return False
    if state.exists and not state.owned:
        notices.append(
            f"Rules not delivered: {target} is not overlay-generated; move its "
            f"content into the primary {LOCAL_RULE} and remove the file"
        )
        return False
    if state.fresh:
        return False
    try:
        atomic_write(target, generated_copy_text(local_text))
    except OverlayError as exc:
        notices.append(f"Rules not delivered: {exc}")
        return False
    return True


# --- rule snapshot -----------------------------------------------------------


def read_optional_rule(path: Path, notices: List[str]) -> Optional[str]:
    if not path_exists(path):
        return None
    try:
        return read_rule(path)
    except OverlayError as exc:
        notices.append(f"Rule file not loaded by overlay: {exc}")
        return None


def labeled_rules(parts: Sequence[Tuple[str, str]]) -> str:
    sections = [f"# {name} (agents-local-overlay)\n\n{text}" for name, text in parts]
    return "\n\n".join(sections)


def over_cap_notice(policy: str, cap: int) -> str:
    return (
        f"Rules not injected: rule text exceeds the {cap}-char {policy} budget; "
        f"shorten {SHARED_RULE}/{LOCAL_RULE} or move rarely needed content to "
        "regular docs opened on demand"
    )


# --- hook emission -----------------------------------------------------------


def notice_lines(notices: Sequence[str]) -> str:
    return "\n".join(NOTICE_PREFIX + notice for notice in notices)


def emit_json(event: str, body: str) -> None:
    payload = {
        "hookSpecificOutput": {
            "hookEventName": event,
            "additionalContext": body,
        }
    }
    sys.stdout.write(json.dumps(payload) + "\n")
    sys.stdout.flush()


def parse_hook_object(hook_input: str, policy: str) -> dict:
    try:
        hook = json.loads(hook_input)
    except (ValueError, TypeError) as exc:
        raise OverlayError(f"policy {policy} requires JSON hook input") from exc
    if not isinstance(hook, dict):
        raise OverlayError(f"policy {policy} requires object hook input")
    return hook


def hook_cwd(hook: dict, policy: str) -> str:
    cwd = hook.get("cwd")
    if not isinstance(cwd, str) or not cwd:
        raise OverlayError(f"policy {policy} requires hook cwd")
    return cwd


# --- Claude policies ---------------------------------------------------------


def claude_session_notices(ctx: RepoContext) -> List[str]:
    notices: List[str] = []
    if not overlay_opted_in(ctx):
        return notices
    if os.environ.get("CLAUDE_CODE_DISABLE_CLAUDE_MDS") == "1":
        notices.append(
            "Rules not delivered: CLAUDE_CODE_DISABLE_CLAUDE_MDS=1 disables the "
            "native CLAUDE.md channel this overlay relies on; unset it and start "
            "a new session"
        )
    notices.extend(worktree_topology_notices(ctx))
    local_exists = path_exists(local_source_path(ctx))
    local_text = read_optional_rule(local_source_path(ctx), notices)
    notices.extend(missing_shared_notices(ctx))
    notices.extend(stray_local_notices(ctx))
    if path_exists(shared_source_path(ctx)):
        read_optional_rule(shared_source_path(ctx), notices)
        try:
            state = bridge_state(ctx.top / CLAUDE_SHARED_BRIDGE, SHARED_BRIDGE_MARKER)
        except OverlayError as exc:
            state = None
            notices.append(f"Rules not delivered: {exc}")
        if state is not None and not state.exists:
            notices.append(
                f"Rules not delivered: {ctx.top / CLAUDE_SHARED_BRIDGE} bridge is "
                f"missing; run agents-overlay-context setup"
            )
        elif state is not None and not state.normalizable:
            notices.append(
                f"Rules not delivered: {ctx.top / CLAUDE_SHARED_BRIDGE} is not the "
                f"single-line {SHARED_BRIDGE_MARKER} bridge; move extra content to "
                f"{SHARED_RULE} and run agents-overlay-context setup"
            )
    if path_exists(local_source_path(ctx)):
        if not ctx.root_is_bare and ctx.top == ctx.root:
            try:
                state = bridge_state(ctx.root / CLAUDE_LOCAL_BRIDGE, LOCAL_BRIDGE_MARKER)
            except OverlayError as exc:
                state = None
                notices.append(f"Rules not delivered: {exc}")
            if state is not None and not state.exists:
                notices.append(
                    f"Rules not delivered: {ctx.root / CLAUDE_LOCAL_BRIDGE} bridge "
                    "is missing; run agents-overlay-context setup"
                )
            elif state is not None and not state.normalizable:
                notices.append(
                    f"Rules not delivered: {ctx.root / CLAUDE_LOCAL_BRIDGE} is not "
                    f"the single-line {LOCAL_BRIDGE_MARKER} bridge; move extra "
                    f"content to {LOCAL_RULE} and run agents-overlay-context setup"
                )
    # An unreadable source is reported above and keeps the existing copy, the
    # same as setup; only an absent source removes an orphan copy.
    if ctx.top in ctx.copy_worktrees and (local_text is not None or not local_exists):
        refresh_generated_copy(ctx.top, local_text, notices)
    return notices


def claude_session_command(event: str, hook: dict) -> int:
    ctx = resolve_context(hook_cwd(hook, "claude-session"))
    notices = claude_session_notices(ctx)
    if notices:
        emit_json(event, notice_lines(notices))
    return 0


def claude_subagent_command(event: str, hook: dict) -> int:
    agent_type = hook.get("agent_type")
    if not isinstance(agent_type, str):
        emit_json(
            event,
            notice_lines(["SubagentStart payload has no string agent_type; rules not injected"]),
        )
        return 0
    if agent_type not in SUBAGENTS_WITHOUT_NATIVE_MEMORY:
        return 0
    ctx = resolve_context(hook_cwd(hook, "claude-subagent"))
    notices: List[str] = missing_shared_notices(ctx) + stray_local_notices(ctx)
    parts: List[Tuple[str, str]] = []
    shared_text = read_optional_rule(shared_source_path(ctx), notices)
    if shared_text is not None:
        parts.append((SHARED_RULE, shared_text))
    local_text = read_optional_rule(local_source_path(ctx), notices)
    if local_text is not None:
        parts.append((LOCAL_RULE, local_text))
    body = labeled_rules(parts) if parts else ""
    if body and len(body) > CLAUDE_MAX_CHARS:
        notices.append(over_cap_notice("claude-subagent", CLAUDE_MAX_CHARS))
        body = ""
    pieces = [piece for piece in (notice_lines(notices), body) if piece]
    if pieces:
        emit_json(event, "\n\n".join(pieces))
    return 0


# --- Codex policies ----------------------------------------------------------


def codex_kiro_precondition_notices(ctx: RepoContext) -> List[str]:
    notices: List[str] = []
    override = ctx.top / CODEX_OVERRIDE
    if path_exists(override):
        notices.append(
            f"Shared rules may be missing: {override} replaces {SHARED_RULE} "
            "for Codex in this worktree; remove it"
        )
    notices.extend(missing_shared_notices(ctx))
    notices.extend(invalid_shared_notices(ctx))
    notices.extend(stray_local_notices(ctx))
    return notices


def missing_shared_notices(ctx: RepoContext) -> List[str]:
    if path_exists(ctx.top / SHARED_RULE):
        return []
    if ctx.top != ctx.root and path_exists(ctx.root / SHARED_RULE):
        return [
            f"Shared rules may be missing: {ctx.top} has no {SHARED_RULE} but the "
            f"primary worktree does; put the shared source in this checkout"
        ]
    return []


def invalid_shared_notices(ctx: RepoContext) -> List[str]:
    shared = ctx.top / SHARED_RULE
    if not path_exists(shared):
        return []
    try:
        read_rule(shared)
    except OverlayError as exc:
        return [f"Shared rules may be missing: {exc}"]
    return []


def stray_local_notices(ctx: RepoContext) -> List[str]:
    if ctx.top == ctx.root:
        return []
    stray = ctx.top / LOCAL_RULE
    if path_exists(stray):
        return [
            f"Rules not delivered: {stray} is not read; the local source lives "
            f"in the primary worktree only — move its content to "
            f"{local_source_path(ctx)}"
        ]
    return []


def codex_hook_command(event: str, hook: dict, policy: str) -> int:
    ctx = resolve_context(hook_cwd(hook, policy))
    if not path_exists(local_source_path(ctx)):
        if stray_local_notices(ctx):
            emit_json(event, notice_lines(codex_kiro_precondition_notices(ctx)))
        return 0
    notices = codex_kiro_precondition_notices(ctx)
    local_text = read_optional_rule(local_source_path(ctx), notices)
    body = labeled_rules([(LOCAL_RULE, local_text)]) if local_text is not None else ""
    if body and len(body) > CODEX_MAX_CHARS:
        notices.append(over_cap_notice(policy, CODEX_MAX_CHARS))
        body = ""
    pieces = [piece for piece in (notice_lines(notices), body) if piece]
    if pieces:
        emit_json(event, "\n\n".join(pieces))
    return 0


# --- Kiro --------------------------------------------------------------------


def kiro_inheritance_refusal(cwd: Optional[Path] = None, fix: bool = False) -> str:
    binary = shutil.which("kiro-cli")
    if not binary:
        return "kiro-cli was not found"

    def read_setting() -> Tuple[bool, object]:
        try:
            proc = subprocess.run(
                [binary, "settings", "list", "--format", "json"],
                cwd=str(cwd) if cwd is not None else None,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=10,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            return False, None
        if proc.returncode != 0:
            return False, None
        try:
            settings = json.loads(proc.stdout.decode("utf-8"))
        except (UnicodeError, json.JSONDecodeError):
            return False, None
        if not isinstance(settings, dict):
            return False, None
        return True, settings.get(KIRO_INHERITANCE_SETTING, "__absent__")

    ok, value = read_setting()
    if not ok:
        return KIRO_VERIFY_REFUSAL
    if value is False:
        return ""
    if fix and (value == "__absent__" or not isinstance(value, bool)):
        try:
            subprocess.run(
                [binary, "settings", KIRO_INHERITANCE_SETTING, "false"],
                cwd=str(cwd) if cwd is not None else None,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=10,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            return KIRO_VERIFY_REFUSAL
        ok, value = read_setting()
        if not ok:
            return KIRO_VERIFY_REFUSAL
        if value is False:
            return ""
    if value is True:
        return (
            f"Kiro {KIRO_INHERITANCE_SETTING} is true; custom agents would not "
            f"inherit {SHARED_RULE}"
        )
    if value == "__absent__":
        return f"Kiro {KIRO_INHERITANCE_SETTING} is absent; {KIRO_FALSE_REMEDIATION}"
    return f"Kiro {KIRO_INHERITANCE_SETTING} must be boolean false; {KIRO_FALSE_REMEDIATION}"


def kiro_body_command(argv: Sequence[str]) -> int:
    if len(argv) != 1:
        fail("agents-overlay-context: kiro-body requires exactly one directory argument")
    ctx = resolve_context(argv[0], require_git=True)
    refusal = kiro_inheritance_refusal(ctx.top, fix=True)
    if refusal:
        fail(f"agents-overlay-context: {refusal}")
    for notice in codex_kiro_precondition_notices(ctx):
        fail(f"agents-overlay-context: {notice}")
    local = local_source_path(ctx)
    if not path_exists(local):
        return 0
    body = labeled_rules([(LOCAL_RULE, read_rule(local))])
    if len(body) > KIRO_MAX_CHARS:
        fail(f"agents-overlay-context: {over_cap_notice('kiro', KIRO_MAX_CHARS)}")
    sys.stdout.write(body + "\n")
    return 0


# --- ignore management -------------------------------------------------------


def git_check_ignore(repo: Path, rel_path: str) -> bool:
    proc = run_git(repo, ["check-ignore", "-q", "--", rel_path], check=False)
    if proc.returncode == 0:
        return True
    if proc.returncode == 1:
        return False
    raise OverlayError(f"git check-ignore failed for {rel_path} in {repo}")


def git_tracked(repo: Path, rel_path: str, icase: bool = False) -> bool:
    magic = "icase,literal" if icase else "literal"
    proc = run_git(
        repo,
        ["ls-files", "--error-unmatch", "--", f":({magic}){rel_path}"],
        check=False,
    )
    if proc.returncode == 0:
        return True
    if proc.returncode == 1:
        return False
    raise OverlayError(f"could not inspect tracking state of {rel_path} in {repo}")


def append_ignore_pattern(ignore_file: Path, pattern: str) -> None:
    existing = b""
    if path_exists(ignore_file):
        existing = read_regular_file_bytes(ignore_file)
        try:
            existing.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise OverlayError(f"{ignore_file} is not UTF-8") from exc
    prefix = "" if not existing or existing.endswith(b"\n") else "\n"
    atomic_write(
        ignore_file,
        existing.decode("utf-8") + prefix + pattern + "\n",
    )


def ignore_targets(ctx: RepoContext) -> List[str]:
    return [LOCAL_RULE, CLAUDE_LOCAL_BRIDGE, KIRO_STEERING_REL]


def ensure_ignores(ctx: RepoContext, changes: List[str], problems: List[str]) -> None:
    if not ctx.checkout_worktrees:
        problems.append("no checkout worktree found to manage ignore patterns")
        return
    in_primary = not ctx.root_is_bare and ctx.top == ctx.root
    for rel_path in ignore_targets(ctx):
        try:
            tracked = [w for w in ctx.checkout_worktrees if git_tracked(w, rel_path)]
            if tracked:
                for worktree in tracked:
                    problems.append(
                        f"{rel_path} is tracked in {worktree}; untrack it before ignoring"
                    )
                continue
            uncovered = [
                w for w in ctx.checkout_worktrees if not git_check_ignore(w, rel_path)
            ]
            if not uncovered:
                continue
            if in_primary and ctx.root in uncovered:
                gitignore = ctx.root / ".gitignore"
                append_ignore_pattern(gitignore, rel_path)
                changes.append(f"{gitignore}: added ignore pattern {rel_path}")
                uncovered = [w for w in uncovered if not git_check_ignore(w, rel_path)]
            if uncovered:
                exclude = append_shared_exclude(ctx, rel_path)
                changes.append(f"{exclude}: added ignore pattern {rel_path}")
                remaining = [w for w in uncovered if not git_check_ignore(w, rel_path)]
                for worktree in remaining:
                    problems.append(
                        f"{rel_path} is still not ignored in {worktree}; check "
                        "negated ignore rules"
                    )
        except OverlayError as exc:
            problems.append(str(exc))


def append_shared_exclude(ctx: RepoContext, rel_path: str) -> Path:
    # The shared info/exclude covers every worktree regardless of which
    # .gitignore each checkout carries.
    exclude = ctx.common / "info" / "exclude"
    try:
        exclude.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise OverlayError(f"could not create {exclude.parent}: {exc}") from exc
    append_ignore_pattern(exclude, rel_path)
    return exclude


# --- setup -------------------------------------------------------------------


def ensure_bridge(
    path: Path, marker: str, changes: List[str], problems: List[str]
) -> None:
    try:
        state = bridge_state(path, marker)
    except OverlayError as exc:
        problems.append(str(exc))
        return
    if not state.exists:
        try:
            atomic_write(path, marker + "\n")
        except OverlayError as exc:
            problems.append(str(exc))
            return
        changes.append(f"{path}: created {marker} bridge")
        return
    if state.exact:
        return
    if state.normalizable:
        try:
            atomic_write(path, marker + "\n")
        except OverlayError as exc:
            problems.append(str(exc))
            return
        changes.append(f"{path}: normalized to {marker} bridge")
        return
    problems.append(
        f"{path} contains content beyond the {marker} import; move that content "
        f"to the rule source file and leave the one-line bridge"
    )


def setup_command(argv: Sequence[str]) -> int:
    project_dir = argv[0] if argv else "."
    ctx = resolve_context(project_dir, require_git=True)
    changes: List[str] = []
    problems: List[str] = []
    ctx = drop_missing_worktrees(ctx, problems)
    problems.extend(worktree_nesting_problems(ctx))

    shared_exists = path_exists(shared_source_path(ctx))
    local_exists = path_exists(local_source_path(ctx))
    if not shared_exists and not local_exists:
        fail(
            f"agents-overlay-context: create {SHARED_RULE} and/or {LOCAL_RULE} "
            "first, then run setup"
        )

    local_text: Optional[str] = None
    if local_exists:
        try:
            local_text = read_rule(local_source_path(ctx))
        except OverlayError as exc:
            problems.append(str(exc))
    if shared_exists:
        try:
            read_rule(shared_source_path(ctx))
        except OverlayError as exc:
            problems.append(str(exc))
        ensure_bridge(ctx.top / CLAUDE_SHARED_BRIDGE, SHARED_BRIDGE_MARKER, changes, problems)

    if local_text is not None:
        if not ctx.root_is_bare:
            ensure_bridge(ctx.root / CLAUDE_LOCAL_BRIDGE, LOCAL_BRIDGE_MARKER, changes, problems)
    if local_text is not None or not local_exists:
        for worktree in ctx.copy_worktrees:
            copy_notices: List[str] = []
            if refresh_generated_copy(worktree, local_text, copy_notices):
                verb = "refreshed" if local_text is not None else "removed orphan"
                changes.append(f"{worktree / CLAUDE_LOCAL_BRIDGE}: {verb} generated copy")
            problems.extend(copy_notices)

    ensure_ignores(ctx, changes, problems)

    for line in changes:
        print(f"changed: {line}")
    for line in problems:
        print(f"problem: {line}", file=sys.stderr)
    if problems:
        return 1
    print("setup: running verify")
    return verify_command([str(ctx.start)])


# --- verify ------------------------------------------------------------------


def parse_cli_version(text: str) -> Optional[Tuple[int, int, int]]:
    match = re.search(r"(\d+)\.(\d+)\.(\d+)", text)
    if not match:
        return None
    return int(match.group(1)), int(match.group(2)), int(match.group(3))


def cli_version_warnings() -> List[str]:
    warnings: List[str] = []
    for name, (low, high) in CLI_VERSION_WINDOWS.items():
        binary = shutil.which(name)
        if not binary:
            continue
        try:
            proc = subprocess.run(
                [binary, "--version"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=10,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            warnings.append(f"could not determine {name} version")
            continue
        version = parse_cli_version(proc.stdout.decode("utf-8", "replace"))
        if version is None:
            warnings.append(f"could not determine {name} version")
        elif not (low <= version <= high):
            pretty = ".".join(str(part) for part in version)
            low_s = ".".join(str(part) for part in low)
            high_s = ".".join(str(part) for part in high)
            warnings.append(
                f"{name} {pretty} is outside the live-verified window "
                f"{low_s}..{high_s}; re-run the live canary before relying on it"
            )
    return warnings


def codex_config_path() -> Path:
    configured = os.environ.get("CODEX_HOME")
    base = Path(configured) if configured else Path.home() / ".codex"
    return base / "config.toml"


CLAUDE_GLOB_UNSUPPORTED = re.compile(r"[{}\[\]()!]")


def claude_glob_to_regex(pattern: str) -> str:
    out: List[str] = []
    i, n = 0, len(pattern)
    while i < n:
        c = pattern[i]
        if c == "*":
            j = i
            while j < n and pattern[j] == "*":
                j += 1
            segment_start = i == 0 or pattern[i - 1] == "/"
            segment_end = j == n or pattern[j] == "/"
            if j - i >= 2 and segment_start and segment_end:
                if j < n:
                    out.append("(?:.*/)?")
                    i = j + 1
                else:
                    out.append(".*")
                    i = j
            else:
                out.append("[^/]*")
                i = j
        elif c == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(c))
            i += 1
    return "^" + "".join(out) + "$"


def claude_md_excluded(patterns: Sequence[str], path: Path) -> Tuple[bool, List[str]]:
    # Evaluates the claudeMdExcludes subset this script understands: exact
    # absolute paths and globs made of **, * and ?, with backslashes normalized.
    # Claude itself matches with picomatch, so patterns using braces, character
    # classes, extglob or negation are reported back as unevaluable, not guessed.
    candidates = {str(path).replace("\\", "/"), str(resolved_or_self(path)).replace("\\", "/")}
    unevaluable: List[str] = []
    for raw in patterns:
        if not isinstance(raw, str) or not raw:
            continue
        pattern = raw.replace("\\", "/")
        if pattern in candidates:
            return True, []
        if CLAUDE_GLOB_UNSUPPORTED.search(pattern):
            unevaluable.append(raw)
            continue
        regex = re.compile(claude_glob_to_regex(pattern))
        if any(regex.match(c) for c in candidates):
            return True, []
    return False, unevaluable


CLAUDE_SETTINGS_LAYERS = (
    ("user", None),
    ("project", ".claude/settings.json"),
    ("local", ".claude/settings.local.json"),
)


def read_claude_settings(path: Path, problems: List[str]) -> Optional[dict]:
    # Settings files are Claude's, not overlay rule files: Claude follows a
    # symlinked settings.json, so this reader must too.
    try:
        data = path.read_bytes().decode("utf-8")
    except FileNotFoundError:
        return None
    except (OSError, UnicodeDecodeError) as exc:
        problems.append(f"could not read {path}: {exc}")
        return None
    try:
        parsed = json.loads(data)
    except json.JSONDecodeError as exc:
        problems.append(f"could not parse {path}: {exc}")
        return None
    return parsed if isinstance(parsed, dict) else None


def claude_settings_findings(ctx: RepoContext) -> Tuple[List[str], List[str]]:
    problems: List[str] = []
    warnings: List[str] = []
    user_path = Path.home() / ".claude" / "settings.json"
    user = read_claude_settings(user_path, problems)
    seen: set = set()
    for worktree in ctx.checkout_worktrees:
        layers = [("user", user_path, user)]
        for name, rel in CLAUDE_SETTINGS_LAYERS:
            if rel is None:
                continue
            p = worktree / rel
            layers.append((name, p, read_claude_settings(p, problems)))

        # disableAllHooks: last layer (highest precedence) that sets it wins.
        disable_source: Optional[Path] = None
        disable_value: Optional[bool] = None
        for _name, p, data in layers:
            if isinstance(data, dict) and "disableAllHooks" in data:
                disable_value = data.get("disableAllHooks")
                disable_source = p
        if disable_value is True:
            msg = (
                f"disableAllHooks is true in {disable_source}; Claude hooks are off, "
                "so this overlay's subagent injection and session notices will not "
                "run — re-enable hooks"
            )
            if msg not in seen:
                seen.add(msg)
                problems.append(msg)

        # claudeMdExcludes: arrays merge across layers.
        patterns: List[str] = []
        for _name, _p, data in layers:
            if isinstance(data, dict):
                value = data.get("claudeMdExcludes")
                if isinstance(value, list):
                    patterns.extend(v for v in value if isinstance(v, str))
        if not patterns:
            continue
        bridges = [worktree / CLAUDE_SHARED_BRIDGE, worktree / CLAUDE_LOCAL_BRIDGE]
        for bridge in bridges:
            if not path_exists(bridge):
                continue
            matched, unevaluable = claude_md_excluded(patterns, bridge)
            if matched:
                msg = (
                    f"claudeMdExcludes matches {bridge}; Claude will not load that "
                    "bridge, so the rules it carries are silently dropped — remove "
                    "the matching pattern"
                )
                if msg not in seen:
                    seen.add(msg)
                    problems.append(msg)
            elif unevaluable:
                msg = (
                    "claudeMdExcludes pattern(s) "
                    + ", ".join(repr(p) for p in unevaluable)
                    + " use brace, character-class, extglob or negation syntax this "
                    f"check does not evaluate; confirm they do not match {bridge}"
                )
                if msg not in seen:
                    seen.add(msg)
                    warnings.append(msg)
    return problems, warnings


def codex_verify_findings(ctx: RepoContext) -> Tuple[List[str], List[str]]:
    problems: List[str] = []
    warnings: List[str] = []
    for base in dict.fromkeys((ctx.top, ctx.root, *ctx.checkout_worktrees)):
        override = base / CODEX_OVERRIDE
        if path_exists(override):
            problems.append(
                f"{override} replaces {SHARED_RULE} for Codex; remove it"
            )
    config_path = codex_config_path()
    if not path_exists(config_path):
        return problems, warnings
    if tomllib is None:
        warnings.append("python tomllib unavailable; Codex config not checked")
        return problems, warnings
    try:
        data = tomllib.loads(read_regular_file_bytes(config_path).decode("utf-8"))
    except (OverlayError, UnicodeDecodeError, tomllib.TOMLDecodeError) as exc:
        problems.append(f"could not parse {config_path}: {exc}")
        return problems, warnings
    fallback = data.get("project_doc_fallback_filenames")
    if fallback not in (None, []):
        problems.append(
            f"{config_path}: project_doc_fallback_filenames must be [] or absent"
        )
    if "project_root_markers" in data:
        problems.append(
            f"{config_path}: project_root_markers changes Codex project-doc "
            "discovery; remove it"
        )
    max_bytes = data.get("project_doc_max_bytes", CODEX_DEFAULT_PROJECT_DOC_MAX_BYTES)
    if not isinstance(max_bytes, int) or max_bytes <= 0:
        problems.append(f"{config_path}: project_doc_max_bytes must be a positive integer")
    else:
        for worktree in ctx.checkout_worktrees:
            shared = worktree / SHARED_RULE
            if not path_exists(shared):
                continue
            try:
                size = len(read_regular_file_bytes(shared))
            except OverlayError:
                continue
            if size > max_bytes:
                problems.append(
                    f"{shared} is {size} bytes, over Codex project_doc_max_bytes "
                    f"{max_bytes}; Codex would truncate the shared rules"
                )
    projects = data.get("projects")
    if isinstance(projects, dict):
        trusted = {
            key
            for key, value in projects.items()
            if isinstance(value, dict) and value.get("trust_level") == "trusted"
        }
        for worktree in ctx.checkout_worktrees:
            candidates = {str(worktree), str(resolved_or_self(worktree))}
            if not candidates & trusted:
                warnings.append(
                    f"{worktree} has no trusted entry in {config_path}; Codex may "
                    "skip native AGENTS.md loading for untrusted projects"
                )
    else:
        for worktree in ctx.checkout_worktrees:
            warnings.append(
                f"{worktree} has no trusted entry in {config_path}; Codex may "
                "skip native AGENTS.md loading for untrusted projects"
            )
    return problems, warnings


def verify_command(argv: Sequence[str]) -> int:
    project_dir = argv[0] if argv else "."
    ctx = resolve_context(project_dir, require_git=True)
    problems: List[str] = []
    warnings: List[str] = []
    ctx = drop_missing_worktrees(ctx, problems)
    problems.extend(worktree_nesting_problems(ctx))

    shared_worktrees = [
        w for w in ctx.checkout_worktrees if path_exists(w / SHARED_RULE)
    ]
    local_exists = path_exists(local_source_path(ctx))
    local_text: Optional[str] = None
    shared_texts: dict = {}
    for worktree in shared_worktrees:
        try:
            shared_texts[worktree] = read_rule(worktree / SHARED_RULE)
        except OverlayError as exc:
            problems.append(str(exc))
    if local_exists:
        try:
            local_text = read_rule(local_source_path(ctx))
        except OverlayError as exc:
            problems.append(str(exc))

    if shared_worktrees:
        for worktree in ctx.checkout_worktrees:
            if worktree not in shared_worktrees:
                problems.append(
                    f"{worktree} has no {SHARED_RULE}; each worktree needs the "
                    "shared source in its checkout (track it or copy it there)"
                )
        for worktree in shared_worktrees:
            bridge = worktree / CLAUDE_SHARED_BRIDGE
            try:
                state = bridge_state(bridge, SHARED_BRIDGE_MARKER)
                if not state.exists:
                    problems.append(f"{bridge} bridge is missing; run setup")
                elif not state.exact:
                    problems.append(
                        f"{bridge} is not the byte-exact single-line "
                        f"{SHARED_BRIDGE_MARKER} bridge; run setup"
                    )
            except OverlayError as exc:
                problems.append(str(exc))

    for worktree in ctx.copy_worktrees:
        stray = worktree / LOCAL_RULE
        if path_exists(stray):
            problems.append(
                f"{stray} exists but the local source lives in the primary "
                f"worktree only; move its content to {local_source_path(ctx)}"
            )

    if local_exists:
        if not ctx.root_is_bare:
            bridge = ctx.root / CLAUDE_LOCAL_BRIDGE
            try:
                state = bridge_state(bridge, LOCAL_BRIDGE_MARKER)
                if not state.exists:
                    problems.append(f"{bridge} bridge is missing; run setup")
                elif not state.exact:
                    problems.append(
                        f"{bridge} is not the byte-exact single-line "
                        f"{LOCAL_BRIDGE_MARKER} bridge; run setup"
                    )
            except OverlayError as exc:
                problems.append(str(exc))
        for worktree in ctx.copy_worktrees:
            copy = worktree / CLAUDE_LOCAL_BRIDGE
            try:
                state = generated_copy_state(copy, local_text)
            except OverlayError as exc:
                problems.append(str(exc))
                continue
            if not state.exists:
                problems.append(f"{copy} generated copy is missing; run setup")
            elif not state.owned:
                problems.append(
                    f"{copy} is not overlay-generated; move its content into the "
                    f"primary {LOCAL_RULE} and remove it"
                )
            elif not state.fresh:
                problems.append(
                    f"{copy} is stale; run setup or start a Claude session there"
                )
    else:
        for worktree in ctx.copy_worktrees:
            copy = worktree / CLAUDE_LOCAL_BRIDGE
            if path_exists(copy):
                try:
                    if generated_copy_state(copy, None).owned:
                        problems.append(
                            f"{copy} is a generated copy but the primary "
                            f"{LOCAL_RULE} source is missing; run setup to remove it"
                        )
                except OverlayError as exc:
                    problems.append(str(exc))

    for rel_path in ignore_targets(ctx):
        for worktree in ctx.checkout_worktrees:
            try:
                if git_tracked(worktree, rel_path, icase=rel_path == KIRO_STEERING_REL):
                    problems.append(
                        f"{rel_path} is tracked in {worktree}; it must stay local-only"
                    )
                elif not git_check_ignore(worktree, rel_path):
                    problems.append(
                        f"{rel_path} is not git-ignored in {worktree}; run setup "
                        "or add the pattern"
                    )
            except OverlayError as exc:
                problems.append(str(exc))

    budget_cases = list(shared_texts.items()) if shared_texts else [(None, None)]
    for worktree, worktree_shared in budget_cases:
        parts = [(SHARED_RULE, worktree_shared)] if worktree_shared is not None else []
        if local_text is not None:
            parts.append((LOCAL_RULE, local_text))
        if not parts:
            continue
        combined = labeled_rules(parts)
        if len(combined) > CLAUDE_MAX_CHARS:
            where = f" with {worktree / SHARED_RULE}" if worktree is not None else ""
            problems.append(
                f"combined rules{where} are {len(combined)} chars, over the "
                f"{CLAUDE_MAX_CHARS}-char Claude subagent hook budget; shorten them"
            )
    if local_text is not None:
        body = labeled_rules([(LOCAL_RULE, local_text)])
        if len(body) > CODEX_MAX_CHARS:
            problems.append(
                f"local rules are {len(body)} chars, over the {CODEX_MAX_CHARS}-char "
                "Codex/Kiro hook budget; shorten them"
            )

    if shared_worktrees or local_exists:
        settings_problems, settings_warnings = claude_settings_findings(ctx)
        problems.extend(settings_problems)
        warnings.extend(settings_warnings)

    codex_problems, codex_warnings = codex_verify_findings(ctx)
    problems.extend(codex_problems)
    warnings.extend(codex_warnings)

    if shutil.which("kiro-cli") is not None:
        refusal = kiro_inheritance_refusal(ctx.top)
        if refusal:
            if "is true" in refusal or "must be boolean" in refusal:
                problems.append(f"kiro: {refusal}")
            else:
                warnings.append(f"kiro: {refusal}")
    for worktree in ctx.checkout_worktrees:
        for parent_rel in (".kiro", ".kiro/steering"):
            parent = worktree / parent_rel
            try:
                if stat.S_ISLNK(parent.lstat().st_mode):
                    problems.append(f"{parent} must not be a symlink")
            except OSError:
                pass
        steering = worktree / KIRO_STEERING_REL
        if not path_exists(steering):
            continue
        try:
            first = read_regular_file_bytes(steering).decode("utf-8", "replace").split("\n", 1)[0]
        except OverlayError as exc:
            problems.append(str(exc))
            continue
        if first != KIRO_STEERING_OWNER:
            problems.append(
                f"{steering} exists but is not overlay-generated; remove or rename it"
            )

    warnings.extend(cli_version_warnings())

    for line in problems:
        print(f"FAIL: {line}")
    for line in warnings:
        print(f"WARN: {line}")
    if not problems:
        print("verify: OK" + (" (with warnings)" if warnings else ""))
    return 1 if problems else 0


# --- claude worktree create --------------------------------------------------


def safe_slug(value: object, label: str) -> str:
    if not isinstance(value, str) or not value:
        raise OverlayError(f"WorktreeCreate hook input missing {label}")
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,79}", value):
        raise OverlayError(f"WorktreeCreate {label} must be a simple slug")
    if value in (".", "..") or value.startswith(".") or value.endswith("."):
        raise OverlayError(f"WorktreeCreate {label} must not be dot-like")
    return value


def slug_component(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9._-]+", "-", value).strip(".-")
    return safe or "repo"


def claude_worktree_base_dir() -> Path:
    configured = os.environ.get(CLAUDE_WORKTREE_DIR_ENV)
    if configured:
        return Path(configured).expanduser()
    return Path.home() / ".cache" / "agents-local-overlay" / "claude-worktrees"


def prepare_dir(path: Path) -> None:
    if path_exists(path):
        try:
            mode = path.lstat().st_mode
        except OSError as exc:
            raise OverlayError(f"could not inspect directory {path}: {exc}") from exc
        if stat.S_ISLNK(mode) or not stat.S_ISDIR(mode):
            raise OverlayError(f"{path} is not a regular directory")
        return
    try:
        path.mkdir(parents=True, exist_ok=False)
    except OSError as exc:
        raise OverlayError(f"could not create directory {path}: {exc}") from exc


def claude_worktree_repo_dir(ctx: RepoContext) -> Path:
    repo_part = slug_component(ctx.root.name)
    repo_key = hashlib.sha256(str(ctx.common).encode("utf-8")).hexdigest()[:12]
    return claude_worktree_base_dir() / f"{repo_part}-{repo_key}"


def claude_worktree_branch(name: str) -> str:
    return f"agents-overlay/{name}"


def git_branch_exists(cwd: Path, branch: str) -> bool:
    proc = run_git(
        cwd, ["rev-parse", "--verify", "--quiet", f"refs/heads/{branch}"], check=False
    )
    if proc.returncode == 0:
        return True
    if proc.returncode == 1:
        return False
    raise OverlayError(f"could not check whether branch {branch} exists")


def ensure_worktree_ignores(ctx: RepoContext, worktree: Path) -> None:
    for rel_path in ignore_targets(ctx):
        if git_tracked(worktree, rel_path):
            raise OverlayError(f"{rel_path} is tracked in {worktree}; untrack it before ignoring")
        if git_check_ignore(worktree, rel_path):
            continue
        exclude = append_shared_exclude(ctx, rel_path)
        if not git_check_ignore(worktree, rel_path):
            raise OverlayError(
                f"{rel_path} is still not ignored in {worktree} after adding it to "
                f"{exclude}; check negated ignore rules"
            )


def discard_claude_worktree(ctx: RepoContext, target: Path, branch: str) -> List[str]:
    """Undo a partially created hook worktree; returns what could not be undone."""
    leftovers: List[str] = []
    removed = run_git(ctx.root, ["worktree", "remove", "--force", str(target)], check=False)
    if removed.returncode != 0:
        leftovers.append(f"worktree {target} still exists")
    deleted = run_git(ctx.root, ["branch", "-D", branch], check=False)
    if deleted.returncode != 0:
        leftovers.append(f"branch {branch} still exists")
    return leftovers


def branch_tip_on_other_ref(cwd: Path, branch: str) -> bool:
    own = f"refs/heads/{branch}"
    proc = run_git(
        cwd,
        ["for-each-ref", "--contains", own, "--format=%(refname)", "refs/heads", "refs/remotes"],
    )
    refs = proc.stdout.decode("utf-8", "replace").split("\n")
    return any(ref and ref != own for ref in refs)


def claude_worktree_create_command() -> int:
    hook = parse_hook_object(sys.stdin.read(), "claude-worktree-create")
    project_dir = hook_cwd(hook, "claude-worktree-create")
    ctx = resolve_context(project_dir, require_git=True)
    name = safe_slug(hook.get("name"), "name")
    repo_dir = claude_worktree_repo_dir(ctx)
    target = repo_dir / name
    branch = claude_worktree_branch(name)
    if resolved_or_self(target) in ctx.worktrees and not target.is_dir():
        raise OverlayError(
            f"{target} is still registered as a worktree but its directory is gone; "
            f"run git worktree prune (and git branch -D {branch} if the branch is "
            "not needed), then retry"
        )
    if path_exists(target):
        raise OverlayError(
            f"worktree target already exists: {target}; choose another name or "
            "remove it with git worktree remove"
        )
    for existing in ctx.worktrees:
        if path_is_within(target, existing):
            raise OverlayError(
                f"worktree target must be outside every existing worktree: {target}"
            )
    if git_branch_exists(ctx.top, branch):
        raise OverlayError(
            f"branch {branch} already exists from an earlier worktree named {name}; "
            f"merge or delete it (git branch -D {branch}) or choose another name"
        )
    local_text: Optional[str] = None
    local = local_source_path(ctx)
    if path_exists(local):
        local_text = read_rule(local)
    prepare_dir(repo_dir.parent)
    prepare_dir(repo_dir)
    base_ref = os.environ.get(CLAUDE_WORKTREE_BASE_ENV, "HEAD")
    run_git(ctx.top, ["worktree", "add", "-q", "-b", branch, str(target), base_ref])
    try:
        if local_text is not None:
            ensure_worktree_ignores(ctx, target)
            copy_notices: List[str] = []
            refresh_generated_copy(target, local_text, copy_notices)
            if copy_notices:
                raise OverlayError(copy_notices[0])
        resolved = target.resolve(strict=True)
    except (OverlayError, OSError) as exc:
        leftovers = discard_claude_worktree(ctx, target, branch)
        detail = str(exc)
        if leftovers:
            detail += "; rollback incomplete: " + ", ".join(leftovers)
        raise OverlayError(detail) from exc
    sys.stdout.write(str(resolved) + "\n")
    return 0


def claude_worktree_remove_command() -> int:
    hook = parse_hook_object(sys.stdin.read(), "claude-worktree-remove")
    raw_path = hook.get("worktree_path")
    if not isinstance(raw_path, str) or not raw_path:
        raise OverlayError("WorktreeRemove hook input missing worktree_path")
    ctx = resolve_context(raw_path, require_git=True)
    target = ctx.top
    if ctx.start != target or target == ctx.root or target not in ctx.worktrees:
        raise OverlayError(f"{raw_path} is not a linked worktree root")
    if target.parent != resolved_or_self(claude_worktree_repo_dir(ctx)):
        raise OverlayError(
            f"{target} was not created by the WorktreeCreate hook; remove it with "
            "git worktree remove"
        )
    branch = claude_worktree_branch(target.name)
    head = run_git(target, ["symbolic-ref", "--quiet", "HEAD"], check=False)
    head_ref = head.stdout.decode("utf-8", "replace").strip()
    if head.returncode != 0 or head_ref != f"refs/heads/{branch}":
        raise OverlayError(
            f"{target} is not on branch {branch}; remove it with git worktree remove"
        )
    # No --force: git refuses a worktree with modified or untracked files, which
    # keeps that work in place; the ignored generated copy does not block removal.
    run_git(ctx.root, ["worktree", "remove", str(target)])
    # Claude surfaces this hook's stderr only in debug logs, so a kept branch
    # becomes visible at the next same-name create instead.
    if branch_tip_on_other_ref(ctx.root, branch):
        run_git(ctx.root, ["branch", "-D", branch])
        return 0
    print(
        f"agents-overlay-context: kept branch {branch}; its commits are on no other "
        f"branch — merge it or run git branch -D {branch} before reusing the name",
        file=sys.stderr,
    )
    return 0


# --- entry -------------------------------------------------------------------


def hook_command(argv: Sequence[str]) -> int:
    if len(argv) < 5:
        fail("agents-overlay-context: missing arguments\n" + usage())
    event = argv[0]
    policy = argv[4]
    hook_input = sys.stdin.read()
    if policy in ("claude-session", "claude-subagent"):
        hook = parse_hook_object(hook_input, policy)
        if policy == "claude-session":
            return claude_session_command(event, hook)
        return claude_subagent_command(event, hook)
    if policy in ("codex-session", "codex-subagent"):
        hook = parse_hook_object(hook_input, policy)
        return codex_hook_command(event, hook, policy)
    fail(f"agents-overlay-context: unknown policy {policy}\n" + usage())
    return 1


def main(argv: Sequence[str]) -> int:
    if not argv:
        fail("agents-overlay-context: missing command\n" + usage())
    command, rest = argv[0], list(argv[1:])
    try:
        if command == "json":
            return hook_command(rest)
        if command == "kiro-body":
            return kiro_body_command(rest)
        if command == "setup":
            return setup_command(rest)
        if command == "verify":
            return verify_command(rest)
        if command == "claude-worktree-create":
            return claude_worktree_create_command()
        if command == "claude-worktree-remove":
            return claude_worktree_remove_command()
        fail(f"agents-overlay-context: unknown command {command}\n" + usage())
        return 1
    except QuietExit:
        return 0
    except OverlayError as exc:
        fail(f"agents-overlay-context: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
