#!/usr/bin/env python3
from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
import tempfile
from pathlib import Path


TARGET_REL = ".kiro/steering/agents-local-overlay.md"
TARGET_PATHSPEC = ":(icase,literal).kiro/steering/agents-local-overlay.md"
OWNER = "<!-- generated by agents-local-overlay; do not edit -->"


class LauncherError(Exception):
    pass


def fail(message: str, code: int = 1) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(code)


def run_git(cwd: Path, args: list[str], check: bool = True) -> subprocess.CompletedProcess[bytes]:
    try:
        proc = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
    except FileNotFoundError as exc:
        raise LauncherError("git is required") from exc
    if check and proc.returncode != 0:
        detail = proc.stderr.decode("utf-8", "replace").strip()
        suffix = f": {detail}" if detail else ""
        raise LauncherError(f"git {' '.join(args)} failed{suffix}")
    return proc


def resolve_top() -> Path:
    proc = run_git(Path.cwd(), ["rev-parse", "--path-format=absolute", "--show-toplevel"], check=False)
    if proc.returncode != 0:
        raise LauncherError("run this launcher inside a Git worktree")
    data = proc.stdout
    if not data.endswith(b"\n"):
        raise LauncherError("could not resolve the Git worktree")
    try:
        return Path(data[:-1].decode("utf-8"))
    except UnicodeDecodeError as exc:
        raise LauncherError("Git worktree path is not UTF-8") from exc


def path_exists(path: Path) -> bool:
    return os.path.lexists(path)


def reject_symlink(path: Path, label: str) -> None:
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        return
    except OSError as exc:
        raise LauncherError(f"could not inspect {label}: {exc}") from exc
    if stat.S_ISLNK(mode):
        raise LauncherError(f"{label} must not be a symlink")


def first_line(path: Path) -> str:
    try:
        with path.open(encoding="utf-8") as f:
            return f.readline().rstrip("\n")
    except (OSError, UnicodeError) as exc:
        raise LauncherError(f"could not read {path}") from exc


def ensure_target_safe(top: Path) -> tuple[Path, Path]:
    kiro_dir = top / ".kiro"
    steering_dir = kiro_dir / "steering"
    target = steering_dir / "agents-local-overlay.md"

    reject_symlink(kiro_dir, ".kiro")
    if path_exists(kiro_dir) and not kiro_dir.is_dir():
        raise LauncherError(f"not a directory: {kiro_dir}")
    reject_symlink(steering_dir, ".kiro/steering")
    if path_exists(steering_dir) and not steering_dir.is_dir():
        raise LauncherError(f"not a directory: {steering_dir}")
    reject_symlink(target, TARGET_REL)
    if path_exists(target) and not target.is_file():
        raise LauncherError(f"reserved path is not a regular file: {target}")
    if target.is_file() and first_line(target) != OWNER:
        raise LauncherError(f"reserved path already contains another document: {target}")

    tracked = run_git(top, ["ls-files", "--error-unmatch", "--", TARGET_PATHSPEC], check=False)
    if tracked.returncode == 0:
        raise LauncherError(f"generated steering file is tracked: {TARGET_REL}")
    if tracked.returncode != 1:
        raise LauncherError("could not inspect tracked steering files")

    ignored = run_git(top, ["check-ignore", "-q", "--", TARGET_REL], check=False)
    if ignored.returncode != 0:
        raise LauncherError(f"add {TARGET_REL} to a git ignore file")

    try:
        kiro_dir.mkdir(exist_ok=True)
        steering_dir.mkdir(exist_ok=True)
    except OSError as exc:
        raise LauncherError(f"could not create Kiro steering directory: {exc}") from exc
    return steering_dir, target


def overlay_body(top: Path, core: Path) -> str:
    proc = subprocess.run(
        [
            sys.executable,
            str(core),
            "raw",
            "SessionStart",
            "cwd:AGENTS.md",
            "-",
            str(top),
            "kiro-launcher",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        detail = proc.stderr.decode("utf-8", "replace").strip()
        raise LauncherError(detail or "overlay helper failed")
    return proc.stdout.decode("utf-8", "replace")


def write_target(steering_dir: Path, target: Path, body: str) -> None:
    tmp_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=steering_dir,
            prefix=".agents-local-overlay.",
            delete=False,
        ) as tmp:
            tmp_path = Path(tmp.name)
            tmp.write(OWNER)
            tmp.write("\n\n")
            tmp.write(body)
        tmp_path.chmod(0o600)
        os.replace(tmp_path, target)
    except OSError as exc:
        raise LauncherError(f"could not write {target}") from exc
    finally:
        if tmp_path is not None:
            try:
                tmp_path.unlink()
            except FileNotFoundError:
                pass
            except OSError:
                pass


def main(argv: list[str]) -> int:
    try:
        kiro_bin = shutil.which("kiro-cli")
        if not kiro_bin:
            fail("kiro-cli-overlay: kiro-cli was not found", 127)
        script_dir = Path(__file__).resolve().parent
        core = script_dir / "agents_overlay_context.py"
        if not core.is_file():
            raise LauncherError(f"missing helper: {core}")
        top = resolve_top()
        steering_dir, target = ensure_target_safe(top)
        write_target(steering_dir, target, overlay_body(top, core))
        os.chdir(top)
        try:
            os.execvpe(kiro_bin, [kiro_bin, "--v3", *argv], os.environ)
        except OSError as exc:
            raise LauncherError(f"could not exec kiro-cli: {exc}") from exc
    except LauncherError as exc:
        print(f"kiro-cli-overlay: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
